Models/Timesheet.cs
using System;
using System.Collections.Generic;

namespace Timesheet_Project.Models
{
    public partial class Timesheet
    {
        public Timesheet()
        {
            TimesheetItems = new HashSet<TimesheetItem>();
        }

        public int TimesheetId { get; set; }
        public int EmpId { get; set; }
        public string State { get; set; } = null!;
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime CreatedAt { get; set; }

        public virtual Employee Emp { get; set; } = null!;
        public virtual ICollection<TimesheetItem> TimesheetItems { get; set; }
    }
}

Controllers/TimesheetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Timesheet_Project.Models;
using Timesheet_Project.ViewModel;
using Timesheet_Project.Utils;

namespace Timesheet_Project.Controllers
{
    public class TimesheetsController : Controller
    {
        private readonly TimesheetDBContext _context;
        //private readonly ITimesheetService _timesheetService;
        public TimesheetsController(TimesheetDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var timesheetDBContext = _context.Timesheets.Include(t => t.Emp);
            return View(await timesheetDBContext.ToListAsync());
        }

        //myTimeSheet
        public async Task<IActionResult> Create(int? timesheet_id)
        //public async Task<IActionResult> Create(int? timesheet_id)
        {
            //var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var emp = _context.Employees.FirstOrDefault(m => m.Id == 1);

            if (emp != null)
            {
                if (timesheet_id.HasValue && timesheet_id < 1)
                {
                    ViewBag.Message = TempData["Message"];
                    return View(null);
                }
                else
                {
                    //ViewBag.emp_number = emp.EmpNumber;
                    var timesheet = _context.Timesheets.Include(m => m.TimesheetItems).OrderByDescending(m => m.TimesheetId).FirstOrDefault(m => m.EmpId == emp.Id);
                    var timesheetModel = new TimesheetModel
                    {
                        Timesheet = timesheet
                    };
                    if (timesheet == null)
                    {
                        timesheetModel.month = DateTime.Now.Month;
                        timesheetModel.year = DateTime.Now.Year;
                    }
                    else
                    {
                        timesheetModel.month = timesheet.StartDate.Month;
                        timesheetModel.year = timesheet.StartDate.Year;
                    }
                    ViewBag.Message = TempData["Message"];
                    return View(timesheetModel);
                }
            }
            return NotFound();
        }

        [HttpPost] //HttpPost for create
        //[PermissionFilter(permission = "timesheet.mytimesheet")]
        public async Task<ActionResult> Create(IFormCollection form_collection)
        {
            var year = Convert.ToInt32(form_collection["year"]);
            var month = Convert.ToInt32(form_collection["month"]);
            var start_date = new DateTime(year, month, 1);
            var end_date = new DateTime(year, month, DateTime.DaysInMonth(year, month));

            //var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var timesheet = await _context.Timesheets.Include(m => m.TimesheetItems)
            .OrderByDescending(m => m.TimesheetId)
             .FirstOrDefaultAsync(m => m.EmpId == 1 && m.StartDate == start_date && m.EndDate == end_date);

            //var emp = _hrmUtilService.GetEmployeeByUserId(userId);

            //var timesheet = await _timesheetService.GetEmployeeTimesheetByDates(start_date, end_date, emp.EmpNumber);
            var timesheetModel = new TimesheetModel
            {
                Timesheet = timesheet
            };
            if (timesheet == null)
            {
                timesheetModel.month = month;
                timesheetModel.year = year;
            }
            else
            {
                timesheetModel.month = timesheet.StartDate.Month;
                timesheetModel.year = timesheet.StartDate.Year;
            }
            return View(timesheetModel);
        }


        // GET: Timesheets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Timesheets == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheets
                .Include(t => t.Emp)
                .FirstOrDefaultAsync(m => m.TimesheetId == id);
            if (timesheet == null)
            {
                return NotFound();
            }

            return View(timesheet);
        }
  
        // GET: Previous Timesheet 
        public async Task<IActionResult> NewTimeSheet(int year, int month)
        {
            //var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //var emp = _hrmUtilService.GetEmployeeByUserId(userId);
            var emp = _context.Employees.FirstOrDefault(m => m.Id == 1);

            //check for existing timesheets
            var start_date = new DateTime(year, month, 1);
            var end_date = new DateTime(year, month, DateTime.DaysInMonth(year, month));
            var timesheet = await _context.Timesheets.Include(m => m.TimesheetItems)
            .OrderByDescending(m => m.TimesheetId)
            .FirstOrDefaultAsync(m => m.EmpId == emp.Id && m.StartDate == start_date && m.EndDate == end_date);

            if (timesheet != null)
            {
                return RedirectToAction("Edit", new { id = timesheet.TimesheetId });
            }

            timesheet = new Timesheet
            {
                StartDate = start_date,
                EndDate = end_date,
                EmpId = emp.Id,
                State = "NOTSUBMITTED",
                CreatedAt = DateTime.Now
            };
            _context.Timesheets.Add(timesheet);
            await _context.SaveChangesAsync();

            return RedirectToAction("Edit", new { id = timesheet.TimesheetId });
        }

        public async Task<IActionResult> Edit(int? id)
        {
            // if its empty return not found 
            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheets
                .Include(m => m.TimesheetItems).ThenInclude(m => m.Project)
                .FirstOrDefaultAsync(m => m.TimesheetId == id);
            if (timesheet == null)
            {
                return NotFound();
            }

            var view_model = new TimesheetModel();
            var items = new List<TimesheetItemViewModel>();
            foreach (var item in timesheet.TimesheetItems)
            {
                items.Add(new TimesheetItemViewModel(item));
            }
            view_model.year = timesheet.StartDate.Year;
            view_model.month = timesheet.EndDate.Month;
            var timeSheetDays = DateUtil.indexMonth(view_model.year, view_model.month);
            view_model.TimesheetDays = timeSheetDays;
            view_model.FirstWeek = timeSheetDays.FirstOrDefault().WeekOfMonth;
            view_model.LastWeek = timeSheetDays.LastOrDefault().WeekOfMonth;
            view_model.Timesheet = timesheet;
            view_model.TimesheetItem = items;// timesheet.TimesheetItem.ToList();
        

            var timesheet_items = timesheet.TimesheetItems;
            //ViewData["Projects"] = new SelectList(_context.Projects.Where(m => m.ProjectId != 1).ToListAsync().Result, "Id", "Name");
            //ViewData["Activities"] = new SelectList(_hrmUtilService.GetActivities().Result, "Id", "Name");
            ViewData["Projects"] = await _context.Projects.ToListAsync();
            //ViewData["Activities"] = _hrmUtilService.GetActivities().Result;
            ViewBag.timesheet_items = timesheet_items;

            ViewBag.EmpId = timesheet.EmpId;
            return View(view_model);
        }

        [HttpPost]
        public IActionResult PostTimesheet(List<TimesheetItem> timesheetItems)
        {
            if (ModelState.IsValid)
            {
                // Construct and save timesheet items
                List<TimesheetItem> itemsToSave = new List<TimesheetItem>();
                foreach (var itemViewModel in timesheetItems)
                {
                    var item = new TimesheetItem
                    {
                        Date = itemViewModel.Date,
                        ProjectId = itemViewModel.ProjectId,
                        WkDuration = itemViewModel.WkDuration,
                        EmpId = itemViewModel.EmpId,
                        Summary = itemViewModel.Summary,
                        Signature = itemViewModel.Signature,
                    };

                    itemsToSave.Add(item);
                }

                // Save the timesheet items to the database
                _context.TimesheetItems.AddRange(itemsToSave);
                _context.SaveChanges();

                // Optionally, you can perform additional operations or redirect to another page
                return RedirectToAction("Index");
            }

            // If the model state is not valid, handle the error or return the view with validation errors
            return View();
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Timesheets == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheets
                .Include(t => t.Emp)
                .FirstOrDefaultAsync(m => m.TimesheetId == id);
            if (timesheet == null)
            {
                return NotFound();
            }

            return View(timesheet);
        }

        // POST: Timesheets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Timesheets == null)
            {
                return Problem("Entity set 'TimesheetDBContext.Timesheets'  is null.");
            }

Views/Timesheets/Create.cshtml
@model Timesheet_Project.ViewModel.TimesheetModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-content">
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            @if (ViewBag.Message != null)
                            {
                                <div class="alert alert-info">
                                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                    @Html.Raw(ViewBag.Message)
                                </div>
                            }
                        </div>
                        <div class="d-flex align-items-center p-3">
                            <h5 class="card-title mb-0 text-uppercase">Last TimeSheet</h5>
                            <div class="ml-auto">
                                <form asp-action="Create" method="post">
                                    <div class="card-body" style="padding:0px;">
                                        <div class="row">
                                            <div class="ml-auto" style="padding: 2px;">
                                                <select asp-for="month" class="form-control" onchange="$('#btn_refresh').click()">
                                                    @* <option>...Select Month...</option> *@
                                                    <option value="1">Jan</option>
                                                    <option value="2">Feb</option>
                                                    <option value="3">Mar</option>
                                                    <option value="4">Apr</option>
                                                    <option value="5">May</option>
                                                    <option value="6">Jun</option>
                                                    <option value="7">Jul</option>
                                                    <option value="8">Aug</option>
                                                    <option value="9">Sep</option>
                                                    <option value="10">Oct</option>
                                                    <option value="11">Nov</option>
                                                    <option value="12">Dec</option>
                                                </select>
                                            </div>
                                            <div class="ml-auto" style="padding: 2px;">
                                                <select asp-for="year" onchange="$('#btn_refresh').click()" class="form-control">
                                                    @for (var i = 2020; i <= DateTime.Now.Year; i++)
                                                    {
                                                        <option value="@i">@i</option>
                                                    }
                                                </select>
                                            </div>
                                            @*<div class="ml-auto" style="padding: 1px; ">
                                                    <button type="submit" class="btn btn-info btn-circle" id="btn_refresh"><i class="fas fa-redo-alt"></i></button>
                                             </div>*@
                                            <div class="ml-auto" style="padding: 2px; line-height: 44px;">
                                                <button type="submit" class="btn btn-info btn-circle" id="btn_refresh">
                                                    <i class="fas fa-redo-alt"></i>
                                                </button>
                                            </div>

                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body">
                                <div class="fc-overflow">
                                    <div id="myEvent"></div>
                                </div>
                            </div>
                        <div class="d-flex align-items-center p-3 mt-2">
                    <div class="ml-auto">
                        @if (Model.Timesheet == null)
                        {
                            <form asp-action="NewTimeSheet" method="post" id="frm_new_timesheet">
                                <input type="hidden" asp-for="year" value="@Model.year" />
                                <input type="hidden" asp-for="month" value="@Model.month" />
                            </form>
                            <a class="btn btn-primary text-white btn-rounded py-2 px-3" href="javascript:document.getElementById('frm_new_timesheet').submit()">Add <i class="fas fa-plus ml-2"></i></a>
                        }
                        else
                        {
                            if (Model.Timesheet.State == "NOTSUBMITTED" || Model.Timesheet.State == "NOTSUBMITTED")
                            {
                                <a asp-controller="Timesheet" asp-action="Submit" asp-route-id="@Model.Timesheet.TimesheetId" class="btn btn-success text-white btn-rounded py-2 px-3">Submit <i class="fa fa-check ml-2"></i></a>
                                <a asp-controller="Timesheet" asp-action="Edit" asp-route-id="@Model.Timesheet.TimesheetId" class="btn btn-info text-white btn-rounded py-2 px-3">Edit <i class="fas fa-edit ml-2"></i></a>
                            }
                        }
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
   </section>
</div>

Views/Timesheets/Delete.cshtml
@model Timesheet_Project.Models.Timesheet

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Timesheet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emp.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TimesheetId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Timesheets/Details.cshtml
@model Timesheet_Project.Models.Timesheet
@using Newtonsoft.Json;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Views/Timesheets/Edit.cshtml
@model Timesheet_Project.ViewModel.TimesheetModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-content">
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-header">Edit Timesheet for @(new DateTime(Model.year, Model.month, 1).ToString("MMMM yyyy"))</h4>
                        </div>
                        <form asp-action="PostTimesheet" method="POST">
                            <input type="hidden" value="@Model.Timesheet.TimesheetId" name="timesheet_id" />
                            @{
                                List<int> allweeks = Model.TimesheetDays.Select(m => m.WeekOfMonth).Distinct().ToList();
                            }
                            <div class="card-body">
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">New Project</label>
                                <div class="col-sm-12 col-md-7">
                                    @{
                                         var project_id = "project_";

                                    }
                                    <select class="@string.Format("form-control pr {0}", project_id)" name="@project_id" asp-items="@(new SelectList(ViewBag.Projects, "ProjectId", "ProjectName"))" onchange="enable_activities(this)">
                                        <option value="">Select Project</option>
                                    </select>
                                </div>
                            </div>
                            </div>
                           @foreach (var i in allweeks)
                            {
                                var week_days = Model.TimesheetDays.Where(e => e.WeekOfMonth == i);
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table table-responsive table-bordered table-striped" id="tbl_@i" style="min-width: 600px;">
                                            <thead>
                                                <tr>
                                                    @foreach (var day in week_days)
                                                    {
                                                        if (day.Date.Month == Model.month)
                                                        {
                                                            var lorh = ""; @*ArrangeUtil.HolidayOrLeave(day.Date, ViewBag.EmpNumber);*@
                                                            @if (!string.IsNullOrEmpty(lorh))
                                                            {
                                                                <th class="bg-secondary" style="text-align:center" width="10%">@day.DayOfWeek.Substring(0, 3) @day.DayOfMonth [@lorh]</th>
                                                            }
                                                            else
                                                            {
                                                                <th class="bg-secondary" style="text-align:center" width="10%">@day.DayOfWeek.Substring(0, 3) @day.DayOfMonth </th>
                                                            }
                                                        }
                                                        else
                                                        {
                                                            <th width="10%"></th>
                                                        }
                                                    }
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var day in week_days)
                                                {
                                                    var row_count = 0;
                                                    row_count += 1;
                                                    var value = "";
                                                    var time_sheet = Model.TimesheetItem.FirstOrDefault(e => e.Date == day.Date);
                                                    if (time_sheet != null)
                                                    {
                                                        //wkduration working with timesheet item view model
                                                        value = time_sheet.WkDuration.ToString();
                                                    }
                                                    if (day.Date.Month == Model.month)
                                                    {
                                                        var read_only = "";
                                                        var name = i + "_" + day.Date.ToString("yyyy-MM-dd") + "_" + row_count;
                                                    <td>
                                                        <div class="input-group">
                                                            <input type="number" @read_only maxlength="2" min="0" max="24" class="form-control small eligible" name="@name" value="@value"> <span class="input-group-btn">
                                                            </span>
                                                        </div>
                                                    </td>
                                                    }
                                                    else
                                                    {
                                                    <td>
                                                        <div class="input-group">
                                                        </div>
                                                    </td>
                                                    }
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            }
                            <div style="float:right;">
                                <button class="btn btn-primary" type="submit">Save</button>
                                <a class="btn btn-warning" asp-controller="Timesheets" asp-action="Index">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts {
    <script src="~/js/timesheet.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Timesheets/Index.cshtml
@model IEnumerable<Timesheet_Project.Models.Timesheet>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
*@

<div class="main-content">
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.State)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.StartDate)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.EndDate)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CreatedAt)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Emp)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model) {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.State)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StartDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EndDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CreatedAt)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Emp.Id)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.TimesheetId">Edit</a> |
                                            <a asp-action="Details" asp-route-id="@item.TimesheetId">Details</a> |
                                            <a asp-action="Delete" asp-route-id="@item.TimesheetId">Delete</a>
                                        </td>
                                    </tr>
                                    }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>